.\" man page create by R# package system.
.TH KNOWLEDGEGRAPH 1 2000-Jan "as.knowledge" "as.knowledge"
.SH NAME
as.knowledge \- direct cast the graph object as a knowledge term
.SH SYNOPSIS
\fIas.knowledge(\fBisland\fR as <generic> NetworkGraph);\fR
.SH DESCRIPTION
.PP
direct cast the graph object as a knowledge term
.PP
.SH OPTIONS
.PP
\fBisland\fB \fR\- -. 
.PP
.SH SEE ALSO
KnowledgeGraph
.SH FILES
.PP
graphR.dll
.PP
