.\" man page create by R# package system.
.TH KNOWLEDGEGRAPH 1 2000-01-01 "knowledgeIslands" "knowledgeIslands"
.SH NAME
knowledgeIslands \- 
.SH SYNOPSIS
\fIknowledgeIslands(\fBgraph\fR as <generic> NetworkGraph, 
\fBweightCut\fR as double = -1, 
\fBidenticalKeys\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
KnowledgeGraph
.SH FILES
.PP
graphR.dll
.PP
