.\" man page create by R# package system.
.TH KNOWLEDGEGRAPH 1 2000-01-01 "networkGraph" "networkGraph"
.SH NAME
networkGraph \- export the graph database as the
.SH SYNOPSIS
\fInetworkGraph(\fBkb\fR as <generic> GraphPool);\fR
.SH DESCRIPTION
.PP
export the graph database as the 
 network graph model for run 
 algorithm debug.
.PP
.SH OPTIONS
.PP
\fBkb\fB \fR\- -. 
.PP
.SH VALUE
.PP
nodes meta: knowledge_type
.PP
.SH SEE ALSO
KnowledgeGraph
.SH FILES
.PP
graphR.dll
.PP
.SH COPYRIGHT
Copyright © 微软中国 2022
