.TH __COSINE 1 2024-Aug "" "__cosine"
.SH NAME
__cosine \- __cosine(va, vb)
.SH SYNOPSIS
\fI__cosine(va, vb)\fR
.SH OPTIONS
.PP
\fBva\fB \fR\- . 
.PP
.PP
\fBvb\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__cosine at graphKbWeb.R:line 80
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2024
