.TH __JACCARD 1 2023-Sep "" "__jaccard"
.SH NAME
__jaccard \- __jaccard(va, vb)
.SH SYNOPSIS
\fI__jaccard(va, vb)\fR
.SH OPTIONS
.PP
\fBva\fB \fR\- . 
.PP
.PP
\fBvb\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__jaccard at graphKbWeb.R:line 73
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2023
