.TH DEFINITION 1 2023-Dec "" "definition"
.SH NAME
definition \- definition(word,
    <i>word.size</i> = <span style='color: green;'>6</span>,
    <i>top</i> = <span style='color: green;'>30</span>,
    <i>graphdb</i> = getOption(graphdb_web))
.SH SYNOPSIS
\fIdefinition(word,
    <i>word.size</i> = <span style='color: green;'>6</span>,
    <i>top</i> = <span style='color: green;'>30</span>,
    <i>graphdb</i> = getOption(graphdb_web))\fR
.SH OPTIONS
.PP
\fBword\fB \fR\- . 
.PP
.PP
\fBword.size\fB \fR\- 6. 
.PP
.PP
\fBtop\fB \fR\- 30. 
.PP
.PP
\fBgraphdb\fB \fR\- getOption(graphdb_web). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.definition at definition.R:line 3
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2023
