.TH IMPORT_VERBS 1 2024-Apr "" "import_verbs"
.SH NAME
import_verbs \- import_verbs(
    <i>graphdb</i> = getOption(graphdb_web))
.SH SYNOPSIS
\fIimport_verbs(
    <i>graphdb</i> = getOption(graphdb_web))\fR
.SH OPTIONS
.PP
\fBgraphdb\fB \fR\- getOption(graphdb_web). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.import_verbs at imports_stopwords.R:line 1
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2024
