.TH LOAD_PUBMED 1 2024-Aug "" "load the pubmed article set stream file and push into database"
.SH NAME
load_pubmed \- load_pubmed(pubmed, file)
.SH SYNOPSIS
\fIload_pubmed(pubmed, file)\fR
.SH OPTIONS
.PP
\fBpubmed\fB \fR\- . the mysql connection to the pubmed database, which could be generates via the ``open_pubmed`` function.
.PP
.PP
\fBfile\fB \fR\- . the local file path to the pubmed article set database file.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_pubmed at load_pubmed.R:line 26
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2024
