.TH ONE_GRAPH 1 2025-Mar "" "The text data will be indexed via the FNV-1a hash algorithm"
.SH NAME
one_graph \- one_graph(tokens,
    <i>phase.size</i> = <span style='color: green;'>3</span>)
.SH SYNOPSIS
\fIone_graph(tokens,
    <i>phase.size</i> = <span style='color: green;'>3</span>)\fR
.SH OPTIONS
.PP
\fBtokens\fB \fR\- . 
.PP
.PP
\fBphase.size\fB \fR\- 3. 
.PP
.SH VALUE
.PP
a dataframe object that contains the graph link data
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.one_graph at text_graph.R:line 42
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
