.TH OPEN_PUBMED 1 2026-Feb "" "open_pubmed"
.SH NAME
open_pubmed \- open_pubmed(user, passwd,
    <i>dbname</i> = <span style='color: brown;'><strong>'pubmed'</strong></span>,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIopen_pubmed(user, passwd,
    <i>dbname</i> = <span style='color: brown;'><strong>'pubmed'</strong></span>,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBuser\fB \fR\- . 
.PP
.PP
\fBpasswd\fB \fR\- . 
.PP
.PP
\fBdbname\fB \fR\- 'pubmed'. 
.PP
.PP
\fBhost\fB \fR\- 'localhost'. 
.PP
.PP
\fBport\fB \fR\- 3306. 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.open_pubmed at load_pubmed.R:line 6
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2026
