.TH PUSH_GRAPH 1 2026-Feb "" "push_graph"
.SH NAME
push_graph \- push_graph(graph.df,
    <i>graphdb</i> = 'getOption'('graphdb_web'))
.SH SYNOPSIS
\fIpush_graph(graph.df,
    <i>graphdb</i> = 'getOption'('graphdb_web'))\fR
.SH OPTIONS
.PP
\fBgraph.df\fB \fR\- . 
.PP
.PP
\fBgraphdb\fB \fR\- 'getOption'('graphdb_web'). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.push_graph at graphKbWeb.R:line 4
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2026
