.TH TEXT_GRAPH 1 2024-Nov "" "create graph object from the given text data"
.SH NAME
text_graph \- text_graph(text,
    <i>phase.size</i> = <span style='color: green;'>6</span>)
.SH SYNOPSIS
\fItext_graph(text,
    <i>phase.size</i> = <span style='color: green;'>6</span>)\fR
.SH OPTIONS
.PP
\fBtext\fB \fR\- . a text collection data
.PP
.PP
\fBphase.size\fB \fR\- 6. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.text_graph at text_graph.R:line 9
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2024
