require(graphQL);
require(JSON);

let text = "Aspirin is only found in individuals who have consumed this drug. Aspirin or acetylsalicylic acid (acetosal) is a drug in the family of salicylates, often used as an analgesic (against minor pains and aches), antipyretic (against fever), and anti-inflammatory. It has also an anticoagulant effect and is used in long-term low-doses to prevent heart attacks and cancer. It was isolated from meadowsweet (Filipendula ulmaria, formerly classified as Spiraea ulmaria) by German researchers in 1839. While their extract was somewhat effective, it also caused digestive problems such as irritated stomach and diarrhoea, and even death when consumed in high doses. In 1853, a French chemist named Charles Frederic Gerhardt neutralized salicylic acid by buffering it with sodium (sodium salicylate) and acetyl chloride, creating acetosalicylic anhydride. Gerhardt's product worked, but he had no desire to market it and abandoned his discovery. In 1897, researcher Arthur Eichengrun and Felix Hoffmann, a research assistant at Friedrich Bayer & Co. in Germany, derivatized one of the hydroxyl functional groups in salicylic acid with an acetyl group (forming the acetyl ester), which greatly reduced the negative effects. This was the first synthetic drug, not a copy of something that existed in nature, and the start of the pharmaceuticals industry. The name 'aspirin' is composed of a- (from the acetyl group) -spir- (from the plant genus Spiraea) and -in (a common ending for drugs at the time). It has also been stated that the name originated by another means. As referring to AcetylSalicylic and 'pir' in reference to one of the scientists who was able to isolate it in crystalline form, Raffaele Piria. Finally 'in' due to the same reasons as stated above. Salicylic acid (which is a naturally occurring substance found in many plants) can be acetylated using acetic anhydride, yielding aspirin and acetic acid as a byproduct. It is a common experiment performed in organic chemistry labs, and generally tends to produce low yields due to the relative difficulty of its extraction from an aqueous state. The trick to getting the reaction to work is to acidify with phosphoric acid and heat the reagents under reflux with a boiling water bath for between 40 minutes and an hour. Aspirin acts as an inhibitor of cyclooxygenase which results in the inhibition of the biosynthesis of prostaglandins. Aspirin also inhibits platelet aggregation and is used in the prevention of arterial and venous thrombosis. (From Martindale, The Extra Pharmacopoeia, 30th ed, p5).";

let g = text_graph(text);

for(par in g) {
    print(par);
    graphQL::push_graph(par);
}