.\" man page create by R# package system.
.TH QUERY 1 2000-Jan "ignore.evidenceLink" "ignore.evidenceLink"
.SH NAME
ignore.evidenceLink \- ignores the given data types when build graph links.
.SH SYNOPSIS
\fIignore.evidenceLink(\fBkb\fR as <generic> EvidenceGraph, 
\fBignores\fR as any);\fR
.SH DESCRIPTION
.PP
ignores the given data types when build graph links.
.PP
.SH OPTIONS
.PP
\fBkb\fB \fR\- -. 
.PP
.PP
\fBignores\fB \fR\- -. 
.PP
.SH SEE ALSO
Query
.SH FILES
.PP
graphR.dll
.PP
