.\" man page create by R# package system.
.TH QUERY 1 2000-Jan "insert" "insert"
.SH NAME
insert \- insert a knowledge node into the graph pool
.SH SYNOPSIS
\fIinsert(\fBkb\fR as <generic> GraphModel, 
\fBknowledge\fR as string, 
\fBtype\fR as string, 
\fBmeta\fR as list = \fB<NULL>\fR, 
\fBselfReference\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
insert a knowledge node into the graph pool
.PP
.SH OPTIONS
.PP
\fBknowledge\fB \fR\- -. 
.PP
.PP
\fBmeta\fB \fR\- -. 
.PP
.PP
\fBselfReference\fB \fR\- 
 the database graph link can be build internal the identical database source
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Query
.SH FILES
.PP
graphR.dll
.PP
