.\" man page create by R# package system.
.TH QUERY 1 2000-Jan "query" "query"
.SH NAME
query \- query knowledge data for a given term
.SH SYNOPSIS
\fIquery(\fBkb\fR as <generic> GraphModel, 
\fBterm\fR as string, 
\fBcutoff\fR as double = 0, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
query knowledge data for a given term
.PP
.SH OPTIONS
.PP
\fBkb\fB \fR\- -. 
.PP
.PP
\fBterm\fB \fR\- -. 
.PP
.PP
\fBcutoff\fB \fR\- -. 
.PP
.SH SEE ALSO
Query
.SH FILES
.PP
graphR.dll
.PP
