.\" man page create by R# package system.
.TH QUERY 1 2000-01-01 "similarity" "similarity"
.SH NAME
similarity \- measure the similarity or identical between two
.SH SYNOPSIS
\fIsimilarity(\fBkb\fR as <generic> GraphPool, 
\fBx\fR as string, 
\fBy\fR as string, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
measure the similarity or identical between two 
 knowledge terms based on the knowledge network 
 that we've build.
.PP
.SH OPTIONS
.PP
\fBkb\fB \fR\- -. 
.PP
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBweight\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Query
.SH FILES
.PP
graphR.dll
.PP
