-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 08:51:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema text_mining
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `text_mining` ;

-- -----------------------------------------------------
-- Schema text_mining
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `text_mining` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `text_mining` ;

-- -----------------------------------------------------
-- Table `text_graph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `text_graph` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `text_graph` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from` INT UNSIGNED NOT NULL,
  `to` INT UNSIGNED NOT NULL,
  `weight` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `count` INT UNSIGNED NOT NULL DEFAULT 0,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `text_graph` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `token_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `token_class` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `token_class` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `token_class` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `word_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `word_token` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `word_token` (
  `id` INT UNSIGNED NOT NULL,
  `token` VARCHAR(1024) NOT NULL,
  `count` INT NOT NULL,
  `class` INT UNSIGNED NOT NULL DEFAULT 1,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'A word token in a given text segment';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `word_token` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `token_UNIQUE` ON `word_token` (`token` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `token_class`
-- -----------------------------------------------------
START TRANSACTION;
USE `text_mining`;
INSERT INTO `token_class` (`id`, `class`, `add_time`) VALUES (1, 'un-assigned', '2023-09-19 00:00:00');

COMMIT;

