.\" man page create by R# package system.
.TH MYSQL 1 2000-1月 "batch_insert" "batch_insert"
.SH NAME
batch_insert \- Create commit task data for make batch insert into current table
.SH SYNOPSIS
\fIbatch_insert(\fBtable\fR as <generic> Model, 
\fBdelayed\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
Create commit task data for make batch insert into current table
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
