.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "check" "check"
.SH NAME
check \- check of the target record is existsed inside the database or not?
.SH SYNOPSIS
\fIcheck(\fBtable\fR as <generic> Model, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
check of the target record is existsed inside the database or not?
.PP
.SH OPTIONS
.PP
\fBtable\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- 
 condition test for where closure
. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
