.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "commit" "commit"
.SH NAME
commit \- commit the batch insert into database
.SH SYNOPSIS
\fIcommit(\fBbatch\fR as <generic> IDataCommitOperation, 
\fBtransaction\fR as <generic> CommitTransaction = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
commit the batch insert into database
.PP
.SH OPTIONS
.PP
\fBbatch\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
