.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "delayed" "delayed"
.SH NAME
delayed \- set delayed options for insert into
.SH SYNOPSIS
\fIdelayed(\fBtable\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set delayed options for insert into
.PP
.SH DETAILS
.PP
this delayed options will be reste to no-delayed after insert has been called
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
