.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "dump_inserts" "dump_inserts"
.SH NAME
dump_inserts \- dump the inserts transaction mysql file
.SH SYNOPSIS
\fIdump_inserts(\fBdata\fR as any, 
\fBdir\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
dump the inserts transaction mysql file
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- A collection of the mysql row data for insert into the database. 
.PP
.PP
\fBdir\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
