.\" man page create by R# package system.
.TH MYSQL 1 2000-1月 "exec" "exec"
.SH NAME
exec \- exec sql and fetch result data as dataframe
.SH SYNOPSIS
\fIexec(\fBtable\fR as <generic> Model, 
\fBsql\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
exec sql and fetch result data as dataframe
.PP
.SH OPTIONS
.PP
\fBtable\fB \fR\- -. 
.PP
.PP
\fBsql\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
