.\" man page create by R# package system.
.TH MYSQL 1 2000-1月 "get_last_sql" "get_last_sql"
.SH NAME
get_last_sql \- get the last mysql query that execute
.SH SYNOPSIS
\fIget_last_sql(\fBmysql\fR as any);\fR
.SH DESCRIPTION
.PP
get the last mysql query that execute
.PP
.SH OPTIONS
.PP
\fBmysql\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
