.\" man page create by R# package system.
.TH MYSQL 1 2000-1月 "imports_sql" "imports_sql"
.SH NAME
imports_sql \- 
.SH SYNOPSIS
\fIimports_sql(\fBuri\fR as any, 
\fBsql\fR as any, 
\fBmysql\fR as string, 
\fBbatch_script\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBuri\fB \fR\- -. 
.PP
.PP
\fBsql\fB \fR\- -. 
.PP
.PP
\fBmysql\fB \fR\- -. 
.PP
.PP
\fBbatch_script\fB \fR\- generates the batch script for make mysql script imports. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
