.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "left_join" "left_join"
.SH NAME
left_join \- mysql left join
.SH SYNOPSIS
\fIleft_join(\fBmodel\fR as <generic> Model, 
\fBtable\fR as string);\fR
.SH DESCRIPTION
.PP
mysql left join
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBtable\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
