.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "open" "open"
.SH NAME
open \- open a mysql connection, construct a database model
.SH SYNOPSIS
\fIopen(\fBuser_name\fR as string, 
\fBpassword\fR as string, 
\fBdbname\fR as string, 
\fBhost\fR as string = "localhost", 
\fBport\fR as integer = 3306, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open a mysql connection, construct a database model
.PP
.SH OPTIONS
.PP
\fBuser_name\fB \fR\- -. 
.PP
.PP
\fBpassword\fB \fR\- -. 
.PP
.PP
\fBdbname\fB \fR\- -. 
.PP
.PP
\fBhost\fB \fR\- -. 
.PP
.PP
\fBport\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
