.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "select" "select"
.SH NAME
select \- make data pull from database
.SH SYNOPSIS
\fIselect(\fBtable\fR as <generic> Model, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
make data pull from database
.PP
.SH OPTIONS
.PP
\fBtable\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
a dataframe object that contains the data that pull from the database
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
