.\" man page create by R# package system.
.TH MYSQL 1 2000-Jan "table" "table"
.SH NAME
table \- Create a table reference
.SH SYNOPSIS
\fItable(\fBmysql\fR as <generic> IDatabase, 
\fBname\fR as string);\fR
.SH DESCRIPTION
.PP
Create a table reference
.PP
.SH OPTIONS
.PP
\fBmysql\fB \fR\- -. 
.PP
.PP
\fBname\fB \fR\- -. 
.PP
.SH SEE ALSO
mysql
.SH FILES
.PP
graphR.dll
.PP
