.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-1月 "add_term" "add_term"
.SH NAME
add_term \- 
.SH SYNOPSIS
\fIadd_term(\fBgraphdb\fR as <generic> graphMySQL, 
\fBterm\fR as string, 
\fBcategory\fR as string = "unclass", 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
