.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-1月 "as.knowledge_builder" "as.knowledge_builder"
.SH NAME
as.knowledge_builder \- cast the mysql object as the knowledge builder object
.SH SYNOPSIS
\fIas.knowledge_builder(\fBgraphdb\fR as <generic> graphMySQL, 
\fBsignature\fR as <generic> SignatureVerifycation = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
cast the mysql object as the knowledge builder object
.PP
.SH OPTIONS
.PP
\fBgraphdb\fB \fR\- -. 
.PP
.PP
\fBsignature\fB \fR\- -. 
.PP
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
