.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-Jan "assign_graph" "assign_graph"
.SH NAME
assign_graph \- assign the knowledge term id to the knowledge nodes
.SH SYNOPSIS
\fIassign_graph(\fBgraphdb\fR as <generic> KnowlegdeBuilder, 
\fBg\fR as <generic> NetworkGraph, 
\fBterm\fR as integer);\fR
.SH DESCRIPTION
.PP
assign the knowledge term id to the knowledge nodes
.PP
.SH OPTIONS
.PP
\fBgraphdb\fB \fR\- -. 
.PP
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBterm\fB \fR\- -. 
.PP
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
