.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-Jan "fetch_table" "fetch_table"
.SH NAME
fetch_table \- 
.SH SYNOPSIS
\fIfetch_table(\fBgraphdb\fR as any, 
\fBheaders\fR as any, 
\fBrow_builder\fR as <generic> RFunction = \fB<NULL>\fR, 
\fBn\fR as integer = 100000, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
