.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-Jan "open.graphdb" "open.graphdb"
.SH NAME
open.graphdb \- 
.SH SYNOPSIS
\fIopen.graphdb(\fBuser_name\fR as string, 
\fBpassword\fR as string, 
\fBhost\fR as string = "localhost", 
\fBport\fR as integer = 3306, 
\fBdbname\fR as string = "graphql");\fR
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
