.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-Jan "pull_nextGraph" "pull_nextGraph"
.SH NAME
pull_nextGraph \- pull a knowledge graph
.SH SYNOPSIS
\fIpull_nextGraph(\fBgraphdb\fR as <generic> KnowlegdeBuilder, 
\fBvocabulary\fR as any, 
\fBid\fR as <generic> UInt32 = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
pull a knowledge graph
.PP
.SH OPTIONS
.PP
\fBgraphdb\fB \fR\- -. 
.PP
.PP
\fBvocabulary\fB \fR\- -. 
.PP
.PP
\fBid\fB \fR\- used for debug test. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
