.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-Jan "pull_nextGraph" "pull_nextGraph"
.SH NAME
pull_nextGraph \- 
.SH SYNOPSIS
\fIpull_nextGraph(\fBgraphdb\fR as <generic> KnowlegdeBuilder, 
\fBvocabulary\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
