.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-1月 "save.knowledge" "save.knowledge"
.SH NAME
save.knowledge \- save the knowledge data json into database as cache
.SH SYNOPSIS
\fIsave.knowledge(\fBgraphdb\fR as <generic> KnowlegdeBuilder, 
\fBseed\fR as integer, 
\fBterm\fR as string, 
\fBunique_hash\fR as string, 
\fBknowledge\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the knowledge data json into database as cache
.PP
.SH OPTIONS
.PP
\fBgraphdb\fB \fR\- -. 
.PP
.PP
\fBseed\fB \fR\- -. 
.PP
.PP
\fBterm\fB \fR\- -. 
.PP
.PP
\fBknowledge\fB \fR\- -. 
.PP
.PP
\fBunique_hash\fB \fR\- 
 the slot key name for get the combination term for generates the hashcode
. 
.PP
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
