.\" man page create by R# package system.
.TH GRAPH_MYSQL 1 2000-Jan "save.knowledge" "save.knowledge"
.SH NAME
save.knowledge \- 
.SH SYNOPSIS
\fIsave.knowledge(\fBgraphdb\fR as <generic> KnowlegdeBuilder, 
\fBseed\fR as integer, 
\fBterm\fR as string, 
\fBknowledge\fR as string);\fR
.SH SEE ALSO
graph_mysql
.SH FILES
.PP
graphR.dll
.PP
