.\" man page create by R# package system.
.TH MSGFILE 1 2000-01-01 "read.graph" "read.graph"
.SH NAME
read.graph \- read target graph database as network graph object
.SH SYNOPSIS
\fIread.graph(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read target graph database as network graph object
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
MsgFile
.SH FILES
.PP
graphR.dll
.PP
