<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PubMedMirror</RootNamespace>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;Rsharp_app_release</Configurations>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Title>Knowledge database model and the algorithm to handle knowledge identification.</Title>
    <Authors>xieguigang &lt;xie.guigang@gcmodeller.org&gt;</Authors>
    <Copyright>Copyright © I@xieguigang.me 2022</Copyright>
    <UseApplicationFramework>True</UseApplicationFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Rsharp_app_release|x64'">
    <OutputPath>../../\assembly\</OutputPath>
    <DocumentationFile>graphQL.xml</DocumentationFile>
    <RemoveIntegerChecks>true</RemoveIntegerChecks>
    <Optimize>false</Optimize>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <DefineConstants>netcore5=1</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>graphQL.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>graphQL.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Rsharp_app_release|AnyCPU'">
    <DocumentationFile>graphQL.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DocumentationFile>graphQL.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DocumentationFile>graphQL.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net5.0|AnyCPU'">
    <RemoveIntegerChecks>true</RemoveIntegerChecks>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DefineConstants>netcore5=1</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\mysqli\LibMySQL\libmysql.vbproj" />
  </ItemGroup>

</Project>
